wetbulb:
  unit_of_measure: F
  outdoor_temp_entity: sensor.khou_temperature
  outdoor_rh_entity: sensor.khou_relative_humidity
  indoor_temp_entity: sensor.4_in_1_sensor_air_temperature
  indoor_rh_entity: sensor.4_in_1_sensor_humidity

sensor:
  - platform: wetbulb
    sensors:
      inside_wet_bulb:
        friendly_name: Wet Bulb Indoors
      outside_wet_bulb:
        friendly_name: Wet Bulb Outdoors
